### ISSUE TITLE
It's working with Alfred 5 

### ISSUE THREAD

**Issue by flexbox** [ilstar/http_status_code#8]
Hey @ilstar 

I just wanted to say thank you because your workflow works like a charm with Alfred 5 ❤️ 

Not an issue —but it's good to know when it works!

**Comment by ilstar** [comment]
Glad to hear that @flexbox , thanks for your compliment!

Given this isn't a real problem, I'm gonna close the issue, feel free to reach out to me if you have any other feedbacks/ideas.
